version: '3.7'
services:

  redis:
    image: redis:6.0-alpine
    container_name: redis
    volumes:
      - redis_data:/data
    restart: unless-stopped

  worker:
    container_name: worker
    depends_on:
      - backend
    build: 
      context: .
      dockerfile: Dockerfile.local
    environment:
      - DJANGO_SETTINGS_MODULE=settings.local
    restart: unless-stopped
    command: poetry run python manage.py run --worker
  
  beat:
    container_name: beat
    build:
      context: .
      dockerfile: Dockerfile.local
    environment:
      - DJANGO_SETTINGS_MODULE=settings.local
    depends_on:
      - worker
    command: poetry run python manage.py run --beat
    restart: unless-stopped

  flower:
    container_name: flower
    build:
      context: .
      dockerfile: Dockerfile.local
    environment:
      - DJANGO_SETTINGS_MODULE=settings.local
    depends_on:
      - worker
    command: poetry run python manage.py run --flower
    restart: unless-stopped
    ports:
      - 5555:5555
    
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.local
    environment:
      - DJANGO_SETTINGS_MODULE=settings.prod
      - PORT=8080
    command: sh scripts/run_server.sh
    restart: unless-stopped   
    ports:
    - 8080:8080

  db:
    image: postgres:12.2-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=stores

volumes:
  redis_data:
  db_data:
