name: Build and Deploy Backend

on:
  push:
    branches:
      - master
    paths-ignore: 
      - "README"
jobs:
  
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: publish image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ramzitannous/Store/backend
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        cache: true

    - name: deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: ~/deploy.sh
    


  